"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.7.
"""

from pathlib import Path
from decouple import config
import dj_database_url
from datetime import timedelta
import os
import logging

# Import logging configuration
try:
    from .logging_config import LOGGING
except ImportError:
    # Fallback logging configuration if import fails
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# React app directory
REACT_APP_DIR = Path(BASE_DIR).parent / 'frontend'
REACT_BUILD_DIR = REACT_APP_DIR / 'dist'

# Security
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', cast=bool)
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Add these production settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])

# Applications
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'debug_toolbar',

    # Project apps
    'users',
    'clubs',
    'events',
    'memberships',
    'shared',
]

# Custom user model
AUTH_USER_MODEL = 'users.CustomUser'

# Middleware
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',        # Must be first for CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# Debug toolbar settings
INTERNAL_IPS = [
    '127.0.0.1',
]

# URL configuration
ROOT_URLCONF = 'core.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [REACT_BUILD_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
try:
    DATABASES = {
        'default': dj_database_url.parse(config('DATABASE_URL'))
    }
    # Add database connection validation
    import django.db
    connection = django.db.connections['default']
    connection.ensure_connection()
    logging.info("Database connection successful")
except Exception as e:
    # Log the specific error
    logging.error(f"Database connection error: {str(e)}")
    # Fallback to SQLite if DATABASE_URL is not valid
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    if not DEBUG:
        logging.warning("Using SQLite in production is not recommended")

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if REACT_BUILD_DIR.exists():
    STATICFILES_DIRS += [REACT_BUILD_DIR]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS (for React frontend on localhost:3000)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'http://localhost:5173',  # Vite's default port
    'http://127.0.0.1:5173',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]-csrftoken',
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',-debug-mode',
    'authorization',
    'content-type',
    'dnt',
    'origin',ONRenderer',
    'user-agent',
    'x-csrftoken',  'rest_framework_simplejwt.authentication.JWTAuthentication',
]       'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
# REST framework settings
REST_FRAMEWORK = {ERMISSION_CLASSES': [_JWT = {
    'DEFAULT_AUTHENTICATION_CLASSES': [',   'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
        'rest_framework.authentication.SessionAuthentication',ys=1),
        'rest_framework.authentication.TokenAuthentication',st_framework.pagination.PageNumberPagination',FRESH_TOKENS': False,
        'rest_framework_simplejwt.authentication.JWTAuthentication', True,
    ], [
    'DEFAULT_PERMISSION_CLASSES': [        'rest_framework.renderers.JSONRenderer',
        'rest_framework.permissions.IsAuthenticated',enderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',SIMPLE_JWT = {
        'rest_framework.renderers.BrowsableAPIRenderer',a(minutes=60),'Bearer',),
    ],1),': 'HTTP_AUTHORIZATION',
}': False,: 'id',
 True,    'USER_ID_CLAIM': 'user_id',
# JWT Settings   'UPDATE_LAST_LOGIN': False,
SIMPLE_JWT = {    'ALGORITHM': 'HS256',    'SIGNING_KEY': SECRET_KEY,    'VERIFYING_KEY': None,    'AUDIENCE': None,


















}    'USER_ID_CLAIM': 'user_id',    'USER_ID_FIELD': 'id',    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',    'AUTH_HEADER_TYPES': ('Bearer',),    'ISSUER': None,    'AUDIENCE': None,    'VERIFYING_KEY': None,    'SIGNING_KEY': SECRET_KEY,    'ALGORITHM': 'HS256',    'UPDATE_LAST_LOGIN': False,    'BLACKLIST_AFTER_ROTATION': True,    'ROTATE_REFRESH_TOKENS': False,    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}
