# Generated by Django 4.2.20 on 2025-04-19 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubcreationrequest",
            name="coordinator",
            field=models.ForeignKey(
                limit_choices_to={"role": "coordinator"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_creation_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="coordinator",
            field=models.OneToOneField(
                limit_choices_to={"role": "coordinator"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinated_club",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="creation_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club",
                to="clubs.clubcreationrequest",
            ),
        ),
    ]
