# Generated by Django 4.2.20 on 2025-05-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={
                "ordering": ["name"],
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
            },
        ),
        migrations.AlterModelOptions(
            name="clubcreationrequest",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Club Creation Request",
                "verbose_name_plural": "Club Creation Requests",
            },
        ),
    ]
