# Generated by Django 4.2.20 on 2025-05-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0003_alter_membership_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["joined_at"],
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
            },
        ),
    ]
