# Generated by Django 4.2.20 on 2025-05-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["username"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
